[project]
name = "wagtail-transfer"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "setuptools>=79.0.0",
    "wagtail==6.0.2",
]
